
  create table "public"."shows" (
    "id" bigint generated by default as identity not null,
    "ensemble_id" bigint not null,
    "name" text not null,
    "tempo_data" jsonb not null,
    "dot_data" jsonb not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."shows" enable row level security;

CREATE UNIQUE INDEX shows_pkey ON public.shows USING btree (id);

alter table "public"."shows" add constraint "shows_pkey" PRIMARY KEY using index "shows_pkey";

alter table "public"."shows" add constraint "shows_ensemble_id_fkey" FOREIGN KEY (ensemble_id) REFERENCES public.ensembles(id) ON DELETE CASCADE not valid;

alter table "public"."shows" validate constraint "shows_ensemble_id_fkey";

grant delete on table "public"."shows" to "anon";

grant insert on table "public"."shows" to "anon";

grant references on table "public"."shows" to "anon";

grant select on table "public"."shows" to "anon";

grant trigger on table "public"."shows" to "anon";

grant truncate on table "public"."shows" to "anon";

grant update on table "public"."shows" to "anon";

grant delete on table "public"."shows" to "authenticated";

grant insert on table "public"."shows" to "authenticated";

grant references on table "public"."shows" to "authenticated";

grant select on table "public"."shows" to "authenticated";

grant trigger on table "public"."shows" to "authenticated";

grant truncate on table "public"."shows" to "authenticated";

grant update on table "public"."shows" to "authenticated";

grant delete on table "public"."shows" to "service_role";

grant insert on table "public"."shows" to "service_role";

grant references on table "public"."shows" to "service_role";

grant select on table "public"."shows" to "service_role";

grant trigger on table "public"."shows" to "service_role";

grant truncate on table "public"."shows" to "service_role";

grant update on table "public"."shows" to "service_role";


  create policy "Ensemble members can read shows"
  on "public"."shows"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.ensemble_memberships em
  WHERE ((em.ensemble_id = shows.ensemble_id) AND (em.user_id = ( SELECT auth.uid() AS uid)) AND ((em.role = 'admin'::text) OR (em.role = 'member'::text))))));



